import Image from "next/image";
import { MapPin } from "lucide-react";
import FAQ from "./FAQ";

export function MapArtwork({large=false}:{large?:boolean}){return <div role="img" aria-label="نقشه موقعیت کارخانه" className={`relative w-full overflow-hidden rounded-[12px] border border-[#e5e7e9] bg-[#e7e9eb] ${large?"h-[390px] md:h-[505px]":"h-[350px] md:h-[380px]"}`}><div className="absolute inset-0 [background-image:linear-gradient(29deg,transparent_45%,#fff_46%,#fff_50%,transparent_51%),linear-gradient(94deg,transparent_46%,#fff_47%,#fff_51%,transparent_52%),linear-gradient(155deg,transparent_47%,#d6d8da_48%,#d6d8da_50%,transparent_51%)] [background-size:145px_105px,190px_135px,120px_160px]"/><div className="absolute -left-12 top-[42%] h-10 w-[125%] -rotate-[8deg] bg-[#f4e993] shadow-[0_0_0_2px_#ded37a]"/><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"><MapPin className="h-12 w-12 fill-[#4b93dd] text-white drop-shadow"/></div><div className="absolute left-3 top-3 flex flex-col rounded bg-white text-xl shadow"><span className="grid h-9 w-9 place-items-center border-b">+</span><span className="grid h-9 w-9 place-items-center">−</span></div></div>}

const faq=[{id:"1",question:"چگونه سفارش خود را ثبت کنم؟",answer:"محصول موردنظر را انتخاب کنید و پس از تعیین سایز، سفارش خود را از طریق سبد خرید نهایی کنید."},{id:"2",question:"آیا امکان خرید حضوری وجود دارد؟",answer:"برای هماهنگی خرید حضوری با واحد پشتیبانی تماس بگیرید."},{id:"3",question:"آیا امکان مرجوعی یا تعویض کالا وجود دارد؟",answer:"بله؛ کالای استفاده‌نشده مطابق شرایط فروشگاه قابل تعویض یا مرجوعی است."}];

export default function ContactSection(){return <section className="bg-white pb-[105px] pt-[118px]"><div className="mx-auto max-w-[1296px] px-5 lg:px-0"><div dir="ltr" className="grid items-center gap-14 lg:grid-cols-[636px_1fr] lg:gap-[100px]"><MapArtwork/><div dir="rtl" className="text-right"><h2 className="text-[28px] font-bold">ارتباط با ما</h2><dl className="mt-[34px] text-[13px] leading-8 text-[#666]"><div className="grid grid-cols-[100px_1fr] border-b border-[#eee] pb-4"><dt className="font-medium text-[#333]">آدرس کارخانه:</dt><dd>تهران، شهرستان بهارستان، شهر گلستان<br/>فلکه دوم خیابان داریوش سلمانی بهارستان۴ پلاک ۱۰۰</dd></div><div className="grid grid-cols-[100px_1fr] border-b border-[#eee] py-4"><dt className="font-medium text-[#333]">تماس:</dt><dd>۰۹۱۲۰۳۰۲۱۴۹<br/>۰۹۱۲۰۳۰۲۱۴۹</dd></div><div className="grid grid-cols-[100px_1fr] items-center pt-4"><dt className="font-medium text-[#333]">فضای مجازی:</dt><dd className="flex items-center gap-4"><Image src="/skill-icons_instagram.png" alt="اینستاگرام" width={24} height={24}/><Image src="/logos_telegram.png" alt="تلگرام" width={24} height={24}/><Image src="/Vector.png" alt="روبیکا" width={24} height={24}/></dd></div></dl></div></div><div className="mt-[125px]"><FAQ items={faq} title="سوالات متداول"/></div></div></section>}
